"""Prepare the current worktree for development.

This command is intentionally cheap and worktree-local. It writes build-system
bridge files, assistant app local secrets, Android local.properties, and
regenerates Xcode projects. It does not install tools and does not build native
dependencies.

Usage:
    prepare_dev
    prepare_dev --platform ios
    prepare_dev --platform android
    prepare_dev --dry_run
"""

from __future__ import annotations

import os
import platform as platform_mod
import shutil
import string
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Literal

from clis.support.paths import REPO_ROOT
from clis.support.native_dependencies.locator import (
    NativeDepsAddress,
    artifact_is_ready,
    bridge_paths,
    ensure_no_legacy_native_deps,
    native_deps_address,
    require_native_deps_ready,
    write_native_deps_bridges,
)
from clis.support.native_dependencies.process_runner import Runner
from clis.support.platform_dependencies.prepare_platform import (
    ANDROID_PROJECTS,
    XCODE_PROJECTS,
    _android_sdk_root,
    _cleanup_android_studio_volatile_state,
    _write_android_local_properties,
)
from clis.tinylib.tinycli import DeriveError
from clis.tinylib.tinylog import log


Platform = Literal["ios", "android"]
ASSISTANT_API_KEY_ENV = "ZEPHR_ASSISTANT_API_KEY"
IOS_ASSISTANT_SECRETS = (
    REPO_ROOT / "apple" / "apps" / "zephr_assistant" / "secrets.xcconfig"
)
ANDROID_ASSISTANT_SECRETS = (
    REPO_ROOT / "android" / "apps" / "zephr_assistant" / "secrets.properties"
)
REPO_XCODE_DERIVED_DATA = REPO_ROOT / "1_build" / "xcode" / "DerivedData"
USER_XCODE_DERIVED_DATA = Path.home() / "Library" / "Developer" / "Xcode" / "DerivedData"
ANDROID_BUILD_DIR_NAMES = ("build", ".cxx")
ANDROID_NATIVE_DEPS_BRIDGE_DIRS = (
    REPO_ROOT / "android" / "sdks" / "zephr_agent_runtime" / "src" / "main" / "cpp" / "native_deps_android",
    REPO_ROOT / "android" / "sdks" / "zephr_agent_tools" / "src" / "main" / "cpp" / "native_deps_android",
)
ANDROID_NATIVE_DEPS_BUILD_TYPES = ("Debug", "Release")
ANDROID_TINYLIB_BRIDGES = {
    REPO_ROOT / "android" / "sdks" / "zephr_agent_runtime" / "src" / "main" / "cpp" / "tinylib": (
        "tinyllm",
        "tinylog",
        "zephr_agent_runtime",
    ),
    REPO_ROOT / "android" / "sdks" / "zephr_agent_tools" / "src" / "main" / "cpp" / "tinylib": (
        "zephr_agent_tools",
    ),
}


@dataclass
class PrepareDevPlan:
    platforms: list[str]
    verbose: bool
    dry_run: bool
    address: NativeDepsAddress
    native_deps_ready: bool
    bridge_files: dict[str, Path]
    android_sdk_root: Path | None
    xcode_projects: list[Path]
    android_projects: list[Path]
    assistant_api_key: str


def _default_platforms() -> list[str]:
    platforms = ["android"]
    if platform_mod.system() == "Darwin":
        platforms.insert(0, "ios")
    return platforms


def _assistant_api_key_from_env() -> str:
    raw_value = os.environ.get(ASSISTANT_API_KEY_ENV, "")
    value = raw_value.strip()
    if raw_value != value:
        raise DeriveError(f"{ASSISTANT_API_KEY_ENV} must not have leading or trailing whitespace")
    if "\n" in value or "\r" in value:
        raise DeriveError(f"{ASSISTANT_API_KEY_ENV} must be a single-line value")
    invalid_chars = sorted(set(value) - set(string.ascii_letters + string.digits + "._~+=-"))
    if invalid_chars:
        display = ", ".join(repr(char) for char in invalid_chars)
        raise DeriveError(
            f"{ASSISTANT_API_KEY_ENV} contains characters that are not safe for generated "
            f"Android properties and Xcode xcconfig files: {display}"
        )
    return value


def _write_assistant_secret_file(path: Path, text: str, *, dry_run: bool) -> None:
    if dry_run:
        print(f"write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_assistant_secrets(platforms: list[str], api_key: str, *, dry_run: bool) -> None:
    if "ios" in platforms and IOS_ASSISTANT_SECRETS.parent.is_dir():
        _write_assistant_secret_file(
            IOS_ASSISTANT_SECRETS,
            "\n".join(
                [
                    "// Generated by prepare_dev from ZEPHR_ASSISTANT_API_KEY.",
                    "// Do not edit; set the environment variable and rerun prepare_dev.",
                    "",
                    f"ZEPHR_ASSISTANT_API_KEY = {api_key}",
                    "",
                ]
            ),
            dry_run=dry_run,
        )
    if "android" in platforms and ANDROID_ASSISTANT_SECRETS.parent.is_dir():
        _write_assistant_secret_file(
            ANDROID_ASSISTANT_SECRETS,
            "\n".join(
                [
                    "# Generated by prepare_dev from ZEPHR_ASSISTANT_API_KEY.",
                    "# Do not edit; set the environment variable and rerun prepare_dev.",
                    "",
                    f"ZEPHR_ASSISTANT_API_KEY={api_key}",
                    "",
                ]
            ),
            dry_run=dry_run,
        )


def _xcode_derived_data_paths_for_projects(
    project_names: list[str],
    *,
    repo_derived_data: Path = REPO_XCODE_DERIVED_DATA,
    user_derived_data: Path = USER_XCODE_DERIVED_DATA,
) -> list[Path]:
    paths: list[Path] = []
    if repo_derived_data.exists():
        paths.append(repo_derived_data)
    elif not user_derived_data.exists():
        return paths

    if user_derived_data.exists():
        for project_name in project_names:
            paths.extend(
                sorted(
                    child
                    for child in user_derived_data.glob(f"{project_name}-*")
                    if child.is_dir()
                )
            )
            exact = user_derived_data / project_name
            if exact.is_dir():
                paths.append(exact)
    return paths


def _remove_tree_after_rename(path: Path) -> None:
    if not path.exists():
        return
    tombstone = path.with_name(
        f".prepare_dev_delete_{path.name}_{os.getpid()}_{time.monotonic_ns()}"
    )
    path.rename(tombstone)
    last_error: OSError | None = None
    for _ in range(3):
        try:
            shutil.rmtree(tombstone)
            return
        except FileNotFoundError:
            return
        except OSError as exc:
            last_error = exc
            time.sleep(0.2)
    if last_error:
        raise last_error


def _clear_xcode_derived_data(project_names: list[str], *, dry_run: bool) -> None:
    for path in _xcode_derived_data_paths_for_projects(project_names):
        if dry_run:
            print(f"rm -rf {path}")
        else:
            log.info("clearing Xcode DerivedData", path=str(path))
            _remove_tree_after_rename(path)


def _android_build_dirs(project_dirs: list[Path]) -> list[Path]:
    paths: list[Path] = []
    seen: set[Path] = set()
    ignored_dir_names = {".gradle", ".idea", ".kotlin"}
    for project_dir in project_dirs:
        if not project_dir.is_dir():
            continue
        candidates: list[Path] = []
        for root, dir_names, _ in os.walk(project_dir):
            dir_names[:] = [
                name
                for name in dir_names
                if name not in ignored_dir_names
                and (not name.startswith(".") or name in ANDROID_BUILD_DIR_NAMES)
            ]
            root_path = Path(root)
            for build_dir_name in ANDROID_BUILD_DIR_NAMES:
                if build_dir_name in dir_names:
                    candidate = root_path / build_dir_name
                    candidates.append(candidate)
                    dir_names.remove(build_dir_name)
        for candidate in sorted(candidates):
            resolved = candidate.resolve()
            if resolved not in seen:
                seen.add(resolved)
                paths.append(candidate)
    return paths


def _clear_android_build_dirs(project_dirs: list[Path], *, dry_run: bool) -> None:
    for path in _android_build_dirs(project_dirs):
        if dry_run:
            print(f"rm -rf {path}")
        else:
            log.info("clearing Android build dir", path=str(path))
            _remove_tree_after_rename(path)


def _replace_symlink(path: Path, target: Path, *, dry_run: bool) -> None:
    if dry_run:
        print(f"ln -sfn {target} {path}")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        current_target = path.resolve(strict=False)
        if current_target == target:
            return
        path.unlink()
    elif path.exists():
        raise DeriveError(f"Refusing to replace non-symlink path: {path}")
    path.symlink_to(target, target_is_directory=True)


def _write_android_native_deps_bridges(address: NativeDepsAddress, *, dry_run: bool) -> None:
    for bridge_dir in ANDROID_NATIVE_DEPS_BRIDGE_DIRS:
        if not bridge_dir.parent.is_dir():
            log.debug("skipping absent Android native deps bridge owner", path=str(bridge_dir))
            continue
        for build_type in ANDROID_NATIVE_DEPS_BUILD_TYPES:
            target = address.root / "android" / "2_installed" / build_type
            if not dry_run and not target.is_dir():
                raise DeriveError(
                    f"Android native deps target missing at {target}. "
                    "Run: uv run prepare_native_deps --platform android"
                )
            link = bridge_dir / build_type
            log.info("writing Android native deps bridge", path=str(link), target=str(target))
            _replace_symlink(link, target, dry_run=dry_run)


def _write_android_tinylib_bridges(*, dry_run: bool) -> None:
    for bridge_dir, names in ANDROID_TINYLIB_BRIDGES.items():
        if not bridge_dir.parent.is_dir():
            log.debug("skipping absent Android tinylib bridge owner", path=str(bridge_dir))
            continue
        for name in names:
            target = REPO_ROOT / "tinylib" / name
            if not dry_run and not target.is_dir():
                raise DeriveError(f"tinylib source target missing at {target}")
            link = bridge_dir / name
            log.info("writing Android tinylib bridge", path=str(link), target=str(target))
            _replace_symlink(link, target, dry_run=dry_run)


def plan_prepare_dev(
    platform: Annotated[list[Platform] | None, "worktree platforms to prepare (default: all applicable)"] = None,
    verbose: Annotated[bool, "show command output"] = False,
    dry_run: Annotated[bool, "print commands without executing"] = False,
    recipe_alias: Annotated[str | None, "mutable dev alias matching prepare_native_deps troubleshooting builds"] = None,
) -> PrepareDevPlan:
    """Write worktree-local bridges and regenerate project files."""
    ensure_no_legacy_native_deps()
    address = native_deps_address(recipe_alias=recipe_alias)
    platforms = list(platform) if platform is not None else _default_platforms()
    return PrepareDevPlan(
        platforms=platforms,
        verbose=verbose,
        dry_run=dry_run,
        address=address,
        native_deps_ready=artifact_is_ready(address.root, address.recipe_hash),
        bridge_files=bridge_paths(),
        android_sdk_root=_android_sdk_root() if "android" in platforms else None,
        xcode_projects=[path for _, path in XCODE_PROJECTS] if "ios" in platforms else [],
        android_projects=[path for _, path in ANDROID_PROJECTS] if "android" in platforms else [],
        assistant_api_key=_assistant_api_key_from_env(),
    )


async def run_prepare_dev(plan: PrepareDevPlan) -> None:
    run = Runner(verbose=plan.verbose, dry_run=plan.dry_run)
    require_native_deps_ready(plan.address)
    write_native_deps_bridges(plan.address, dry_run=plan.dry_run)
    _write_assistant_secrets(plan.platforms, plan.assistant_api_key, dry_run=plan.dry_run)

    if "android" in plan.platforms:
        _cleanup_android_studio_volatile_state(plan.dry_run)
        _clear_android_build_dirs(
            [project_dir for _, project_dir in ANDROID_PROJECTS],
            dry_run=plan.dry_run,
        )
        _write_android_native_deps_bridges(plan.address, dry_run=plan.dry_run)
        _write_android_tinylib_bridges(dry_run=plan.dry_run)
        sdk_root = plan.android_sdk_root or _android_sdk_root()
        if not sdk_root.exists():
            raise DeriveError(
                f"Android SDK not found at {sdk_root}. "
                "Run: uv run prepare_platform_tools --platform android"
            )
        for name, project_dir in ANDROID_PROJECTS:
            if not project_dir.is_dir():
                log.debug(
                    f"skipping {name} local.properties; project does not exist yet",
                    path=str(project_dir),
                )
                continue
            log.info(f"writing {name} local.properties", path=str(project_dir))
            _write_android_local_properties(project_dir, sdk_root, plan.dry_run)

    if "ios" in plan.platforms:
        _clear_xcode_derived_data(
            [name for name, _ in XCODE_PROJECTS],
            dry_run=plan.dry_run,
        )
        xcodegen = shutil.which("xcodegen")
        if not xcodegen:
            raise DeriveError("xcodegen not found. Run: uv run prepare_platform_tools --platform ios")
        for name, project_dir in XCODE_PROJECTS:
            log.info(f"generating {name}", path=str(project_dir))
            await run([xcodegen, "generate"], cwd=project_dir)


def main() -> None:
    from clis.tinylib.tinycli import Pipeline

    pipeline = Pipeline("prepare_dev")
    pipeline.stage("dev", plan_prepare_dev, run_prepare_dev)
    pipeline.main()
