"""Zephr Agent core native inference engine"""

from collections.abc import Mapping, Sequence


def format_tool_call_prompt(model_family: str, tool_name: str, tool_description: str, params: Sequence[tuple[str, str, str, Sequence[str], bool]], user_message: str, system_message: str = '', prompt_profile: str = '') -> str:
    """Format a tool-call prompt using the selected model-family formatter"""

def format_tool_call_completion(model_family: str, tool_name: str, tool_description: str, params: Sequence[tuple[str, str, str, Sequence[str], bool]], arguments: Mapping[str, str], include_function_response: bool = True) -> str:
    """
    Format a tool-call completion using the selected model-family formatter
    """

def set_log_level(level: str) -> None:
    """Set native log level (trace/debug/info/warn/error)"""

def detect_model_family(path: str) -> str:
    """Detect model family from .litertlm bundle"""

def list_bundle_sections(path: str) -> list[tuple[str, int]]:
    """List .litertlm bundle sections as (type, byte_size) tuples"""

def inspect_litertlm_bundle(path: str) -> list:
    """
    Inspect .litertlm bundle sections, signatures, tensor names, and tensor shapes
    """

def run_gemma4_vision_smoke(path: str, num_patches: int = 2304) -> dict:
    """Run Gemma4 vision encoder+adapter on a synthetic patch tensor"""

def run_gemma4_vlm_text_smoke(path: str, prompt: str = 'Describe the image.', num_patches: int = 2304, max_tokens: int = 16) -> dict:
    """Run Gemma4 synthetic image embeddings through the text decoder"""

def run_gemma4_vlm_rgb888(path: str, rgb: bytes, width: int, height: int, row_stride: int, prompt: str = 'Describe the image.', max_tokens: int = 64, encoder_delegate: str = 'cpu', decoder_delegate: str = 'cpu') -> dict:
    """Run Gemma4 VLM on an RGB888 image buffer"""

def run_engine_init_smoke(llm_model: str, rag_embedding: str = '', vlm_model: str = '', llm_plan: str = 'cpu', rag_plan: str = 'cpu', vlm_plan: str = 'gpu', num_threads: int = 0) -> dict:
    """
    Initialize TinyLLMEngine with explicit role plans and report prepared capabilities
    """

class Tokenizer:
    def __init__(self) -> None: ...

    def load(self, arg: str, /) -> bool: ...

    def encode(self, arg: str, /) -> list[int]: ...

    def decode(self, arg: Sequence[int], /) -> str: ...

    def piece_to_id(self, arg: str, /) -> int: ...

    def id_to_piece(self, arg: int, /) -> str: ...

    def vocab_size(self) -> int: ...

class InferenceEngine:
    def reset(self) -> None: ...

    def prefill(self, arg: Sequence[int], /) -> bool: ...

    def decode(self, token_id: int, temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0) -> int: ...

    def decode_with_logits(self, token_id: int, temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0, top_n: int = 10) -> tuple: ...

    def activation_dim(self) -> int: ...

    def decode_with_logits_and_activations(self, token_id: int, temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0, top_n: int = 10) -> tuple: ...

    def constrained_decode(self, tok: Tokenizer, pending_token: int, tool_name: str, params: Sequence[tuple[str, Sequence[str]]], temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0, diag_top_k: int = 8) -> tuple: ...

    def generate_tool_call(self, tool_name: str, tool_description: str, params: Sequence[tuple[str, str, str, Sequence[str], bool]], user_message: str, temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0, system_message: str = '', prompt_profile: str = '') -> tuple: ...

    def generate_tool_call_stats(self, tool_name: str, tool_description: str, params: Sequence[tuple[str, str, str, Sequence[str], bool]], user_message: str, temperature: float = 0.0, top_k: int = 40, top_p: float = 1.0, system_message: str = '', prompt_profile: str = '') -> dict: ...

    def generate_text(self, user_message: str, system_message: str = '', max_tokens: int = 256, temperature: float = 0.699999988079071, top_k: int = 40, top_p: float = 0.949999988079071) -> tuple: ...

    def generate_text_stats(self, user_message: str, system_message: str = '', max_tokens: int = 256, temperature: float = 0.699999988079071, top_k: int = 40, top_p: float = 0.949999988079071) -> dict: ...

    def generate_tool_aware_text_stats(self, tools: Sequence[tuple[str, str, Sequence[tuple[str, str, str, Sequence[str], bool]]]], user_message: str, system_message: str = '', max_tokens: int = 256, temperature: float = 0.0, top_k: int = 40, top_p: float = 0.949999988079071, reserve_output_tokens: int = 0) -> dict: ...

    def generate_tool_aware_text_from_prompt_stats(self, tools: Sequence[tuple[str, str, Sequence[tuple[str, str, str, Sequence[str], bool]]]], prompt: str, max_tokens: int = 256, temperature: float = 0.0, top_k: int = 40, top_p: float = 0.949999988079071, reserve_output_tokens: int = 0) -> dict: ...

    def generate_text_from_prompt_stats(self, prompt: str, max_tokens: int = 256, temperature: float = 0.0, top_k: int = 40, top_p: float = 0.949999988079071) -> dict: ...

    def continue_after_tool_response_stats(self, tool_response: str, max_tokens: int = 256, temperature: float = 0.0, top_k: int = 40, top_p: float = 0.949999988079071, reserve_output_tokens: int = 0) -> dict: ...

    def continue_tool_aware_text_stats(self, tools: Sequence[tuple[str, str, Sequence[tuple[str, str, str, Sequence[str], bool]]]], prompt_suffix: str, max_tokens: int = 256, temperature: float = 0.0, top_k: int = 40, top_p: float = 0.949999988079071, reserve_output_tokens: int = 0) -> dict: ...

    def gemma4_mtp_debug_verify(self, user_message: str, system_message: str = '') -> dict: ...

    @property
    def prefill_seq_len(self) -> int: ...

    @property
    def current_pos(self) -> int: ...

    @property
    def gemma4_mtp_enabled(self) -> bool: ...

    @property
    def gemma4_mtp_available(self) -> bool: ...

class RagEngine:
    def embed(self, text: str, task_type: str = 'query') -> list[float]: ...

    def add(self, id: str, embedding: Sequence[float], lat: float = 0.0, lon: float = 0.0) -> None: ...

    def clear(self) -> None: ...

    def query(self, text: str, lat: float = 0.0, lon: float = 0.0, radius_m: float = 0.0, top_k: int = 5, similarity_threshold: float = 0.30000001192092896) -> list: ...

    def query_visual(self, text: str, lat: float = 0.0, lon: float = 0.0, radius_m: float = 0.0, top_k: int = 5, similarity_threshold: float = 0.25) -> list: ...

    def query_by_embedding(self, embedding: Sequence[float], lat: float = 0.0, lon: float = 0.0, radius_m: float = 0.0, top_k: int = 5, similarity_threshold: float = 0.30000001192092896) -> list: ...

    @property
    def corpus_size(self) -> int: ...

    @property
    def embedding_dim(self) -> int: ...

    @property
    def max_seq_len(self) -> int: ...

class ZephrAgentRuntime:
    def __init__(self) -> None: ...

    def init(self, gpu: bool = False, num_threads: int = 0, llm_model: str = '', rag_embedding: str = '', vlm_model: str = '', llm_plan: str = '', rag_plan: str = '', vlm_plan: str = '', gemma4_mtp_enabled: bool = False, gemma4_gpu_precision: int = -1, gemma4_kv_cache_max_len: int = 0, gemma4_constrained_verify_batch: int = -1, gemma4_mtp_trust_verify_kv: bool = True, gemma4_mtp_adaptive_enabled: bool = True, gemma4_mtp_adaptive_min_cycles: int = 4, gemma4_mtp_adaptive_min_saved_per_cycle: float = 0.5, gemma4_mtp_trace: bool = False, diagnostic_gemma4_prefill_by_decode: bool = False, diagnostic_gemma4_prefill_max_chunk: int = 0, diagnostic_gemma4_constrained_verify_trace: bool = False, diagnostic_gemma4_constrained_verify_max_accept: int = 0) -> bool: ...

    def drain_model_lifecycle_timings(self) -> list: ...

    def describe_image_rgb888(self, rgb: bytes, width: int, height: int, row_stride: int, prompt: str = 'Describe the image.', max_tokens: int = 0) -> dict: ...

    def generate_text_stats(self, user_message: str, system_message: str = '', max_tokens: int = 256, temperature: float = 0.699999988079071, top_k: int = 40, top_p: float = 0.949999988079071) -> dict: ...

    def release(self) -> None: ...

    def clear_loaded_corpus(self) -> None: ...

    @property
    def corpus_size(self) -> int: ...

class Engine:
    def __init__(self) -> None: ...

    def init(self, gpu: bool = False, num_threads: int = 0, llm_model: str = '', rag_embedding: str = '', gemma4_mtp_enabled: bool = False, gemma4_gpu_precision: int = -1, gemma4_kv_cache_max_len: int = 0, gemma4_constrained_verify_batch: int = -1, gemma4_mtp_trust_verify_kv: bool = True, gemma4_mtp_adaptive_enabled: bool = True, gemma4_mtp_adaptive_min_cycles: int = 4, gemma4_mtp_adaptive_min_saved_per_cycle: float = 0.5, gemma4_mtp_trace: bool = False, diagnostic_gemma4_prefill_by_decode: bool = False, diagnostic_gemma4_prefill_max_chunk: int = 0, diagnostic_gemma4_constrained_verify_trace: bool = False, diagnostic_gemma4_constrained_verify_max_accept: int = 0) -> bool: ...

    def release(self) -> None: ...

    @property
    def text(self) -> InferenceEngine: ...

    @property
    def llm(self) -> InferenceEngine: ...

    @property
    def rag(self) -> RagEngine: ...
